// Generated by https://quicktype.io

export interface AzureVariableGroupInfo {
  variables: VariableGroupVariables;
  id: number;
  type: string;
  name: string;
  description: string;
  createdBy: EdBy;
  createdOn: string;
  modifiedBy: EdBy;
  modifiedOn: string;
  isShared: boolean;
  variableGroupProjectReferences: null;
}

export interface EdBy {
  displayName: string;
  id: string;
  uniqueName: string;
}

export interface VariableGroupVariables {
  [x: string]: { value: string };
  auto_created: { value: string };
  name: { value: string };
  tribe: { value: string };
  skip_sonarqube: { value: string };
  skip_rdm: { value: string };
  private_agent_pool: { value: string };
  AUTOMATED: { value: string };
}

// Generated by https://quicktype.io

export interface AzureDistributedVariableGroup {
  variables: VariableGroupVariables;
  id: number;
  type: string;
  name: string;
  description: string;
  createdBy: EdBy;
  createdOn: string;
  modifiedBy: EdBy;
  modifiedOn: string;
  isShared: boolean;
  variableGroupProjectReferences: VariableGroupProjectReference[];
}

export interface EdBy {
  displayName: string;
  id: string;
  uniqueName: string;
}

export interface VariableGroupProjectReference {
  projectReference: VariableGroupProjectReference;
  name: string;
  description: string;
}

export interface VariableGroupProjectReference {
  id: string;
  name: string;
}

export interface VariableGroupVariables {
  auto_created: VariableGroupVariablesAutomated;
  name: VariableGroupVariablesAutomated;
  tribe: VariableGroupVariablesAutomated;
  skip_sonarqube: VariableGroupVariablesAutomated;
  skip_rdm: VariableGroupVariablesAutomated;
  private_agent_pool: VariableGroupVariablesAutomated;
  AUTOMATED: VariableGroupVariablesAutomated;
}

export interface VariableGroupVariablesAutomated {
  value: string;
}
