
// Generated by https://quicktype.io

export interface AzureServiceConnectionInfo {
  data:                             Data;
  id:                               string;
  name:                             string;
  type:                             string;
  url:                              string;
  createdBy:                        CreatedBy;
  description:                      string;
  authorization:                    Authorization;
  isShared:                         boolean;
  isReady:                          boolean;
  owner:                            string;
  serviceEndpointProjectReferences: ServiceEndpointProjectReference[];
}

export interface Authorization {
  parameters: Parameters;
  scheme:     string;
}

export interface Parameters {
  clusterContext: string;
}

export interface CreatedBy {
  displayName: string;
  url:         string;
  _links:      Links;
  id:          string;
  uniqueName:  string;
  imageUrl:    string;
  descriptor:  string;
}

export interface Links {
  avatar: Avatar;
}

export interface Avatar {
  href: string;
}

export interface Data {
  authorizationType:    string;
  acceptUntrustedCerts: string;
}

export interface ServiceEndpointProjectReference {
  projectReference: ProjectReference;
  name:             string;
  description:      string;
}

export interface ProjectReference {
  id:   string;
  name: string;
}
